@startuml
class PermissionsRepositoryIn {
    + PermissionsRepositoryIn(context:DBContext)
}
class "GenericRepositoryIn`1"<T> {
}
"GenericRepositoryIn`1" "<Permissions>" <|-- PermissionsRepositoryIn
@enduml
